name: CD

on:
  push:
    branches: [main]

env:
  NODE_VERSION: 26.x

jobs:
  bump-version:
    name: Bump package.json Version
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[CI/CD]') }}
    outputs:
      tag-name: ${{ steps.lib-bump.outputs.newTag }}

    steps:
      - uses: actions/checkout@v6
        with:
          # This is a fine-grained Github personal access token
          # for resource owner "politie" (needs admin approval)
          # and only repository "politie/sherlock"
          # with the following "Repository permissions":
          # - "Contents" (Access: Read and write),
          # - "Metadata" (Access: Read-only, this is mandatory).
          token: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}

      - name: Bump version
        id: lib-bump
        uses: phips28/gh-action-bump-version@v11.0.4
        with:
          tag-prefix: "v"
          commit-message: "[CI/CD]: bump to {{version}}"

  github-release:
    name: Release on Github
    needs: bump-version
    if: startsWith(needs.bump-version.outputs.tag-name, 'v')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ needs.bump-version.outputs.tag-name }}

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ needs.bump-version.outputs.tag-name }}

  npm-release:
    name: Release on NPM
    needs: bump-version
    if: startsWith(needs.bump-version.outputs.tag-name, 'v')
    runs-on: ubuntu-latest
    permissions:
      # This workflow is configured in NPM as a trusted publisher for all four packages.
      # The id-token permission allows the workflow to publish to NPM.
      id-token: write

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ needs.bump-version.outputs.tag-name }}

      - name: Use node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Release sherlock
        run: npm publish ./dist/sherlock

      - name: Release sherlock-proxy
        run: npm publish ./dist/sherlock-proxy

      - name: Release sherlock-rxjs
        run: npm publish ./dist/sherlock-rxjs

      - name: Release sherlock-utils
        run: npm publish ./dist/sherlock-utils
